import {
  Nav,
  NavbarContainer,
  NavLogo,
  NavIcon,
  ThemeButton,
  FilterButton,
  Ul,
  NavLink,
  NavList,
} from "../styledComponents/styledNav";

import {
  CardContainer,
  ImgContainer,
  Img,
  Title,
  Text,
  CardBody,
  CardButton,
  CardLink,
} from "../styledComponents/styledCard";
import {
  FormGroup,
  Input,
  SearchButton,
} from "../styledComponents/styledSearch";
import { GlobalStyle, Container } from "../styledComponents/globalStyles";
import { Button } from "../styledComponents/styledButton";
import {
  MovieContainer,
  MovieContent,
  MovieImgDiv,
  MovieImg,
  MovieContentText,
  MovieContentTitle,
  MovieText,
  CastContainer,
  CastContent,
  CastImgDiv,
  CastImg,
  CastContentText,
  CastText,
} from "../styledComponents/styledDetailCard";

import {
  InputContainer,
  LoginContainer,
} from "../styledComponents/styledLogin";

import {
  FavoriteIcon,
  WatchedIcon,
  FavoriteIconFill,
  WatchedIconFill,
  InstagramIcon,
  TwitterIcon,
  LogOutIcon,
} from "../styledComponents/icons";

import {
  ProfileContent,
  ProfileImgDiv,
  ProfileImg,
  ProfileContentText,
  ProfileContentTitle,
  ProfileText,
  ProfileLink,
} from "../styledComponents/styledProfile";
export {
  Nav,
  NavbarContainer,
  NavLogo,
  NavIcon,
  ThemeButton,
  FilterButton,
  Ul,
  NavList,
  NavLink,
  CardContainer,
  CardBody,
  ImgContainer,
  Img,
  Title,
  Text,
  CardButton,
  FormGroup,
  Input,
  Button,
  GlobalStyle,
  Container,
  SearchButton,
  CardLink,
  MovieContainer,
  MovieContent,
  MovieImgDiv,
  MovieImg,
  MovieContentText,
  MovieContentTitle,
  MovieText,
  CastContainer,
  CastContent,
  CastImgDiv,
  CastImg,
  CastContentText,
  CastText,
  InputContainer,
  LoginContainer,
  FavoriteIcon,
  WatchedIcon,
  FavoriteIconFill,
  WatchedIconFill,
  InstagramIcon,
  TwitterIcon,
  LogOutIcon,
  ProfileContent,
  ProfileImgDiv,
  ProfileImg,
  ProfileContentText,
  ProfileContentTitle,
  ProfileText,
  ProfileLink,
};
